<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Morrow\\' => array($baseDir . '/main/_libs', $baseDir . '/main/_models', $vendorDir . false),
);
